---
title: "Panel data model examples"
format: 
    html:
        embed-resources: true
        code-fold: true
        df-print: paged
        theme: cosmo
        toc: true
        toc-depth: 3
        toc-location: left
        self-contained: true
        
knitr: 
  opts_chunk: 
    echo: false
    message: false
    warning: false

---


```{r}
library(plm)
library(dplyr)
library(wooldridge)
library(ggplot2)
```
# Exploratory data analysis

```{r}
data(jtrain)

jtrain1 <- jtrain %>% filter(year == 1988, grant == 0)
jtrain2 <- jtrain %>% filter(year == 1988, grant == 1)

quantile(jtrain1$lscrap-jtrain1$lscrap_1,na.rm = TRUE)
quantile(jtrain2$lscrap-jtrain2$lscrap_1,na.rm = TRUE)
```

How many firms report the scrap rate?
```{r}
 jtrain %>% group_by(year) %>% summarise(nz=  sum(is.na(lscrap)), n = n())
```

```{r}
lm(lscrap~d88 + d89+grant+grant_1, data= jtrain) %>% summary
```


```{r}
lm(lscrap~  d89+ lscrap_1+grant+grant_1, data= jtrain) %>% summary
```


```{r}
plm(lscrap~d88 + d89+grant+grant_1+union, data= pdata.frame(jtrain,index=c("fcode", "year")), effect = "individual", model = "random") %>% summary
```



```{r}
jtrain1 <- jtrain[,c(2,1,3:ncol(jtrain))]
p1 <- plm(lscrap~d88 + d89+grant+grant_1+union, data= jtrain1, effect = "individual", model = "random")


summary(p1, vcovHC(p1, method="white1"))
```

```{r}
jtrain1 <- jtrain[,c(2,1,3:ncol(jtrain))]
plm(lscrap~d88 + d89+grant+grant_1+union, data= jtrain1, effect = "individual", model = "within") %>% summary
```